expirement_base_path: "/scratch/itee/uqswan37/balance_training/TAS-query-original"

collection_tsv: "/scratch/itee/uqswan37/balance_training/dataset/msmarco/collection.tsv"

collection_batch_size: 2048
query_batch_size: 48

query_sets:
  <msmarco>:
    queries_tsv: "/scratch/itee/uqswan37/balance_training/dataset/msmarco/msmarco-test2020-queries.tsv"
    qrels: "/scratch/itee/uqswan37/balance_training/dataset/msmarco/2020qrels-pass.txt"
    binarization_point: 2 # what minimum relevant grade to assume for binarized metrics (mrr, recall ...)
    top_n: 1000 # how many results to return
#  <name_of_set2...>: # optional more than 1 query sets
#    queries_tsv: <TODO: path to a single .tsv file with id<tab>text>
#    qrels: <TODO: path to a trec-style qrels file>
#    binarization_point: 1 # what minimum relevant grade to assume for binarized metrics (mrr, recall ...)
#    top_n: 100 # how many results to return