#
# pairwise supervision (via static scores)
#
train_pairwise_distillation: True
loss: "margin-mse"

#
# in batch teacher (via dynamic teacher)
#
in_batch_negatives: False
in_batch_neg_lambda: 0.75
in_batch_main_pair_lambda: 1
in_batch_neg_loss: "margin-mse" #KLDivTeacherList

dynamic_teacher: False
dynamic_teacher_in_batch_scoring: False

train_tsv: "/scratch/itee/uqswan37/balance_training/dataset/msmarco/triples_for_random.tsv"
#
# tas-balanced sampler
#
dynamic_sampler: False

#
# general train settings
#
batch_size_train: 32
run_dense_retrieval_eval: True