collection_batch_size: 2048
query_batch_size: 48

onnx_use_inference: False
dataloader_num_workers: 10 # 0 means only using the main thread (not recommended)


token_block_size: 50000 # every n vectors create a new numpy memory mapped array file
token_dim: 768 # sets the output dimension of the model
token_dtype: "float16" # sets the dtype (either float16 or float32)

#
# general index
#
faiss_index_type: "hnsw" # or full,ivf,hnsw,scann
faiss_use_gpu: True

#
# hnsw settings
#
faiss_hnsw_graph_neighbors: 128
faiss_hnsw_efConstruction: 128 # higher is more accurate and slower to construct
faiss_hnsw_efSearch: 128

#
# ivf settings
#
faiss_ivf_search_probe_count: 500
faiss_ivf_list_count: 2000